config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :status_updates, only: [:new, :create]

  resources :comments, only: [:new, :create]

  root 'conversation_items#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  # Associations
  has_one :conversation_item, as: :item

  # Delegations
  delegate :created_at, :author, to: :conversation_item

  # Validations
  validates :content, presence: true

  # Scopes
  scope :with_conversation_items, -> { includes(:conversation_item).order('conversation_items.created_at': :desc) }
end

app/models/conversation_item.rb
class ConversationItem < ApplicationRecord
  # Associations
  belongs_to :author, class_name: 'User'
  belongs_to :item, polymorphic: true, optional: false

  # Scopes
  scope :latest_first, -> { order(created_at: :desc) }
end

app/models/status_update.rb
class StatusUpdate < ApplicationRecord
  # Enums
  enum status: {
    proposed: 0,
    planned: 1,
    cancelled: 2,
    early_development: 3,
    on_hold: 4,
    alpha: 5,
    beta: 6,
    live: 7,
    deprecated: 8,
    end_of_life: 9,
  }

  # Associations
  has_one :conversation_item, as: :item

  # Delegations
  delegate :created_at, :author, to: :conversation_item

  # Validations
  validates :status, presence: true

  validate :validate_status_has_changed, on: :create

  # Scopes
  scope :with_conversation_items, -> { includes(:conversation_item).order('conversation_items.created_at': :desc) }

  # The current status of the project. Can be nil.
  def self.current
    StatusUpdate.with_conversation_items.first
  end

  # The status update just before this one. Can be nil.
  def previous_status_update
    self.class
        .with_conversation_items
        .where('conversation_items.created_at < ?', conversation_item.created_at)
        .first
  end

  # The status just before this one. Can be nil.
  def previous_status
    previous_status_update&.status
  end

  # Validates that the status of the project is changed by this update.
  def validate_status_has_changed
    latest_status_update = self.class.current

    return unless latest_status_update.present?

    if status == latest_status_update.status
      errors.add(:status, 'The project already has this status')
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)

    @conversation_item = ConversationItem.new(author: current_user, item: @comment)

    respond_to do |format|
      if @comment.save && @conversation_item.save
        format.html { redirect_to root_url, notice: "Comment was successfully posted." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/conversation_items_controller.rb
class ConversationItemsController < ApplicationController
  before_action :authenticate_user!

  def index
    @conversation_items = ConversationItem.latest_first

    @current_status = StatusUpdate.current&.status&.humanize
  end
end

app/controllers/status_updates_controller.rb
class StatusUpdatesController < ApplicationController
  before_action :authenticate_user!

  def new
    @status_update = StatusUpdate.new
  end

 def create
    @status_update = StatusUpdate.new(status_update_params)

    @conversation_item = ConversationItem.new(author: current_user, item: @status_update)

    respond_to do |format|
      if @status_update.save && @conversation_item.save
        format.html { redirect_to root_url, notice: "Project status was successfully updated." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  def status_update_params
    params.require(:status_update).permit(:status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/conversation_items_helper.rb
module ConversationItemsHelper
end

app/helpers/status_updates_helper.rb
module StatusUpdatesHelper
end

app/views/comments/_comment.html.erb
<p id="<%= dom_id comment %>">
  <%= comment.content %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit 'Post' %>
  </div>
<% end %>

app/views/comments/new.html.erb
<h1>Post a comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to conversation", root_path %>
</div>

app/views/conversation_items/_conversation_item.html.erb
<fieldset id="<%= dom_id conversation_item %>">
  <legend><%= conversation_item.author.email %></legend>

  <%= render conversation_item.item %>

  <small><%= conversation_item.created_at.to_formatted_s(:short) %></small>
</fieldset>

app/views/conversation_items/_empty_state.html.erb
<p><i>No history yet. Post a comment or set the projects status!</i></p>

app/views/conversation_items/index.html.erb
<%= render 'shared/navigation' %>

<% if @current_status.present? %>
  <h2>Current project status:</h2>
  <h1><%= @current_status %></h1>
  <hr>
<% end %>

<h2>Conversation history:</h2>
<%= render @conversation_items %>
<%= render 'empty_state' if @conversation_items.empty? %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project Conversation History</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
    <% end %>

    <% if flash[:alert] %>
      <div class="alert"><%= flash[:alert] %></div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/shared/_navigation.html.erb
<fieldset>
  <%= link_to 'Post a comment', new_comment_path %>
  |
  <%= link_to 'Update the project status', new_status_update_path %>
  |
  <%= link_to 'Sign out', destroy_user_session_path, data: { "turbo-method": :delete } %>
</fieldset>

app/views/status_updates/_form.html.erb
<%= form_with(model: status_update) do |form| %>
  <% if status_update.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(status_update.errors.count, "error") %> prohibited this status_update from being saved:</h2>

      <ul>
        <% status_update.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.select :status, StatusUpdate.statuses.keys.map { |s| [s.humanize, s] } %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/status_updates/_status_update.html.erb
<h2 id="<%= dom_id status_update %>">
  <% if status_update.previous_status.present? %>
    <%= status_update.previous_status.humanize %>
    => <%= status_update.status.humanize %>
  <% else %>
    <%= status_update.status.humanize %>
  <% end %>
</h2>

app/views/status_updates/new.html.erb
<h1>New status update</h1>

<%= render "form", status_update: @status_update %>

<br>

<div>
  <%= link_to "Back to conversation", root_path %>
</div>